/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linaer_algo.refinder.ui;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import linaer_algo.refinder.database.IngredientDAO;
import linaer_algo.refinder.database.RecipeDAO;
import linaer_algo.refinder.model.Recipe;
import linaer_algo.refinder.model.Ingredient;
import linaer_algo.refinder.algorithm.RabinKarp;
/**
 *
 * @author Joko1
 */
public class MainFrame extends javax.swing.JFrame {
    
    private int currentActiveRecipeId = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        loadButtonIcon(btnDashboard, "/home.png", 25);
        loadButtonIcon(btnRecipes, "/cookbook.png", 25);
        loadButtonIcon(btnInventory, "/fridge.png", 25);
        loadButtonIcon(btnFavorites, "/star.png", 25);
        loadButtonIcon(btnLog, "/history.png", 25);
        
        setActiveButton(btnDashboard);
        
        // --- CUSTOM TABLE STYLING ---
        // Change the header background to your dark orange
        tblResults.getTableHeader().setBackground(new java.awt.Color(160, 58, 19)); 
        // Change the header text color to white
        tblResults.getTableHeader().setForeground(new java.awt.Color(255, 255, 255)); 
        // Change the font to match your theme (Bold, Size 14)
        tblResults.getTableHeader().setFont(new java.awt.Font("Century Gothic", java.awt.Font.BOLD, 14));
        tblResults.getTableHeader().setOpaque(true);
        
        // Bonus: Make the rows a little taller so the text isn't squished!
        tblResults.setRowHeight(30);
        
        // --- CUSTOM TABLE ROW STYLING ---
        tblResults.setFont(new java.awt.Font("Century Gothic", java.awt.Font.PLAIN, 13));
        tblResults.setForeground(new java.awt.Color(93, 39, 14)); 
        tblResults.setSelectionBackground(new java.awt.Color(160, 58, 19)); 
        tblResults.setSelectionForeground(new java.awt.Color(255, 255, 255)); 

        // --- ALIGN THE PERCENTAGE TO THE RIGHT ---
        javax.swing.table.DefaultTableCellRenderer rightRenderer = new javax.swing.table.DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tblResults.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);
        
        if (!linaer_algo.refinder.database.IngredientDAO.ingredientExists("chicken")) {
            linaer_algo.refinder.database.IngredientDAO.addIngredient(new linaer_algo.refinder.model.Ingredient(0, "chicken", 1.0, "kg"));
            linaer_algo.refinder.database.IngredientDAO.addIngredient(new linaer_algo.refinder.model.Ingredient(0, "garlic", 3.0, "cloves"));
            linaer_algo.refinder.database.IngredientDAO.addIngredient(new linaer_algo.refinder.model.Ingredient(0, "soy sauce", 1.0, "bottle"));
            System.out.println("Test ingredients added successfully!");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnFavorites = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnRecipes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnlContent = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblGreeting = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        btnAutoMatch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResults = new javax.swing.JTable();
        lblInventoryCount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        pnlRecipes = new javax.swing.JPanel();
        pnlInventory = new javax.swing.JPanel();
        pnlFavorites = new javax.swing.JPanel();
        pnlLog = new javax.swing.JPanel();
        pnlRecipeDetails = new javax.swing.JPanel();
        lblRecipeImage = new javax.swing.JLabel();
        lblRecipeTitle = new javax.swing.JLabel();
        lblRecipeCuisine = new javax.swing.JLabel();
        lblRecipeTime = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRecipeIngredients = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRecipeInstructions = new javax.swing.JTextArea();
        btnCooked = new javax.swing.JButton();
        lblMatchScore = new javax.swing.JLabel();
        lblMissingItems = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 248, 222));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(255, 248, 222));

        jPanel1.setBackground(new java.awt.Color(160, 58, 19));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 4, new java.awt.Color(93, 52, 21)));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 248, 222));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copy.png"))); // NOI18N
        jLabel1.setText("ReFinder");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(-30);

        btnDashboard.setBackground(new java.awt.Color(255, 248, 222));
        btnDashboard.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(93, 39, 14));
        btnDashboard.setText("   Dashboard");
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setIconTextGap(15);
        btnDashboard.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnInventory.setBackground(new java.awt.Color(255, 248, 222));
        btnInventory.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(93, 39, 14));
        btnInventory.setText(" Inventory");
        btnInventory.setFocusPainted(false);
        btnInventory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventory.setIconTextGap(15);
        btnInventory.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnInventory.addActionListener(this::btnInventoryActionPerformed);

        btnFavorites.setBackground(new java.awt.Color(255, 248, 222));
        btnFavorites.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnFavorites.setForeground(new java.awt.Color(93, 39, 14));
        btnFavorites.setText(" Favorites");
        btnFavorites.setFocusPainted(false);
        btnFavorites.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFavorites.setIconTextGap(15);
        btnFavorites.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnFavorites.addActionListener(this::btnFavoritesActionPerformed);

        btnLog.setBackground(new java.awt.Color(255, 248, 222));
        btnLog.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnLog.setForeground(new java.awt.Color(93, 39, 14));
        btnLog.setText(" Cooking Log");
        btnLog.setFocusPainted(false);
        btnLog.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLog.setIconTextGap(15);
        btnLog.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnLog.addActionListener(this::btnLogActionPerformed);

        btnRecipes.setBackground(new java.awt.Color(255, 248, 222));
        btnRecipes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRecipes.setForeground(new java.awt.Color(93, 39, 14));
        btnRecipes.setText("  Recipes");
        btnRecipes.setFocusPainted(false);
        btnRecipes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRecipes.setIconTextGap(15);
        btnRecipes.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnRecipes.addActionListener(this::btnRecipesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFavorites, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecipes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFavorites, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlContent.setLayout(new java.awt.CardLayout());

        pnlDashboard.setBackground(new java.awt.Color(255, 248, 222));
        pnlDashboard.setPreferredSize(new java.awt.Dimension(3000, 760));

        lblGreeting.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lblGreeting.setForeground(new java.awt.Color(160, 58, 19));
        lblGreeting.setText("Good Morning!");

        lblSubtitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(93, 39, 14));
        lblSubtitle.setText("What do you wanna cook today?");

        btnAutoMatch.setBackground(new java.awt.Color(160, 58, 19));
        btnAutoMatch.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAutoMatch.setForeground(new java.awt.Color(255, 248, 222));
        btnAutoMatch.setText("What can I cook?");
        btnAutoMatch.addActionListener(this::btnAutoMatchActionPerformed);

        txtSearch.setBackground(new java.awt.Color(160, 58, 19));
        txtSearch.setForeground(new java.awt.Color(255, 248, 222));

        btnSearch.setBackground(new java.awt.Color(160, 58, 19));
        btnSearch.setForeground(new java.awt.Color(255, 248, 222));
        btnSearch.setText("Search");

        tblResults.setBackground(new java.awt.Color(242, 230, 185));
        tblResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Recipe name", "Cuisine", "Missing Ingredients", "Match Percentage %"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResults);

        lblInventoryCount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblInventoryCount.setForeground(new java.awt.Color(160, 58, 19));
        lblInventoryCount.setText("Items in Inventory: ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(160, 58, 19));
        jLabel3.setText("Total  Recipes: 60");
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jSeparator2.setBackground(new java.awt.Color(160, 58, 19));

        jLabel2.setBackground(new java.awt.Color(160, 58, 19));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(160, 58, 19));
        jLabel2.setText("Manual Search:");

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAutoMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGreeting)))
                    .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlDashboardLayout.createSequentialGroup()
                            .addComponent(lblInventoryCount)
                            .addGap(1423, 1423, 1423)
                            .addComponent(jLabel3))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1666, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblGreeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(41, 41, 41)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAutoMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventoryCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20))
        );

        pnlContent.add(pnlDashboard, "pnlDashboard");

        pnlRecipes.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout pnlRecipesLayout = new javax.swing.GroupLayout(pnlRecipes);
        pnlRecipes.setLayout(pnlRecipesLayout);
        pnlRecipesLayout.setHorizontalGroup(
            pnlRecipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1782, Short.MAX_VALUE)
        );
        pnlRecipesLayout.setVerticalGroup(
            pnlRecipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );

        pnlContent.add(pnlRecipes, "pnlRecipes");

        pnlInventory.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pnlInventoryLayout = new javax.swing.GroupLayout(pnlInventory);
        pnlInventory.setLayout(pnlInventoryLayout);
        pnlInventoryLayout.setHorizontalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1782, Short.MAX_VALUE)
        );
        pnlInventoryLayout.setVerticalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );

        pnlContent.add(pnlInventory, "pnlInventory");

        pnlFavorites.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout pnlFavoritesLayout = new javax.swing.GroupLayout(pnlFavorites);
        pnlFavorites.setLayout(pnlFavoritesLayout);
        pnlFavoritesLayout.setHorizontalGroup(
            pnlFavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1782, Short.MAX_VALUE)
        );
        pnlFavoritesLayout.setVerticalGroup(
            pnlFavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );

        pnlContent.add(pnlFavorites, "pnlFavorites");

        pnlLog.setBackground(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1782, Short.MAX_VALUE)
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );

        pnlContent.add(pnlLog, "pnlLog");

        pnlRecipeDetails.setBackground(new java.awt.Color(255, 248, 222));

        lblRecipeImage.setText("jLabel4");
        lblRecipeImage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(160, 58, 19)));

        lblRecipeTitle.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblRecipeTitle.setForeground(new java.awt.Color(160, 58, 19));
        lblRecipeTitle.setText("jLabel4");

        lblRecipeCuisine.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblRecipeCuisine.setForeground(new java.awt.Color(160, 58, 19));
        lblRecipeCuisine.setText("jLabel4");

        lblRecipeTime.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRecipeTime.setForeground(new java.awt.Color(160, 58, 19));
        lblRecipeTime.setText("jLabel5");

        btnBack.setBackground(new java.awt.Color(160, 58, 19));
        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        txtRecipeIngredients.setBackground(new java.awt.Color(255, 248, 222));
        txtRecipeIngredients.setColumns(20);
        txtRecipeIngredients.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtRecipeIngredients.setForeground(new java.awt.Color(160, 58, 19));
        txtRecipeIngredients.setLineWrap(true);
        txtRecipeIngredients.setRows(5);
        txtRecipeIngredients.setWrapStyleWord(true);
        txtRecipeIngredients.setBorder(null);
        jScrollPane2.setViewportView(txtRecipeIngredients);

        txtRecipeInstructions.setBackground(new java.awt.Color(255, 248, 222));
        txtRecipeInstructions.setColumns(20);
        txtRecipeInstructions.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtRecipeInstructions.setForeground(new java.awt.Color(160, 58, 19));
        txtRecipeInstructions.setLineWrap(true);
        txtRecipeInstructions.setRows(5);
        txtRecipeInstructions.setWrapStyleWord(true);
        txtRecipeInstructions.setBorder(null);
        jScrollPane3.setViewportView(txtRecipeInstructions);

        btnCooked.setBackground(new java.awt.Color(160, 58, 19));
        btnCooked.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCooked.setText("I COOKED THIS");
        btnCooked.addActionListener(this::btnCookedActionPerformed);

        lblMatchScore.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMatchScore.setText("jLabel4");

        lblMissingItems.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        lblMissingItems.setText("jLabel5");

        javax.swing.GroupLayout pnlRecipeDetailsLayout = new javax.swing.GroupLayout(pnlRecipeDetails);
        pnlRecipeDetails.setLayout(pnlRecipeDetailsLayout);
        pnlRecipeDetailsLayout.setHorizontalGroup(
            pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecipeCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecipeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMatchScore, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMissingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)
                        .addGap(39, 39, 39)))
                .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCooked, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlRecipeDetailsLayout.setVerticalGroup(
            pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRecipeCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRecipeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMatchScore, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMissingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCooked, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pnlContent.add(pnlRecipeDetails, "pnlRecipeDetails");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritesActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnFavorites);
        
        pnlContent.removeAll();
        pnlContent.add(pnlFavorites);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnFavoritesActionPerformed

    private void btnRecipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipesActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnRecipes);
        
        pnlContent.removeAll();
        pnlContent.add(pnlRecipes);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnRecipesActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnDashboard); // Highlight the button
        
        // Tell the CardLayout to show the Dashboard panel
        pnlContent.removeAll();
        pnlContent.add(pnlDashboard);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnInventory);
        
        pnlContent.removeAll();
        pnlContent.add(pnlInventory);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnLog);
        
        pnlContent.removeAll();
        pnlContent.add(pnlLog);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnAutoMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoMatchActionPerformed
        // TODO add your handling code here:
        // 1. Get the table model and clear old results
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblResults.getModel();
        model.setRowCount(0);

        // 2. Fetch User Inventory (NOW AS INGREDIENT OBJECTS)
        java.util.List<linaer_algo.refinder.model.Ingredient> myInventory = linaer_algo.refinder.database.IngredientDAO.getAllIngredients();

        // 3. Fetch All Recipes
        java.util.List<linaer_algo.refinder.model.Recipe> allRecipes = linaer_algo.refinder.database.RecipeDAO.getAllRecipes();
        java.util.List<Object[]> matchResults = new java.util.ArrayList<>();

        // 4. Run the True Rolling Hash + Quantity Check
        for (linaer_algo.refinder.model.Recipe recipe : allRecipes) {
            
            // Get the required ingredients WITH their quantities
            java.util.List<linaer_algo.refinder.model.Ingredient> requiredIngredients = linaer_algo.refinder.database.RecipeDAO.getRecipeIngredients(recipe.getId());
            
            // Use the new upgraded methods!
            double matchScore = linaer_algo.refinder.algorithm.RabinKarp.calculateQuantityMatch(requiredIngredients, myInventory);
            java.util.List<String> missing = linaer_algo.refinder.algorithm.RabinKarp.getMissingQuantityIngredients(requiredIngredients, myInventory);
            
            String missingItems = String.join(", ", missing);
            if (missingItems.isEmpty()) {
                missingItems = "None! Ready to cook! 🍳";
            }
            
            String formattedScore = String.format("%.1f%%", matchScore);

            matchResults.add(new Object[]{
                recipe.getName(), 
                recipe.getCuisine(), 
                missingItems, 
                formattedScore,
                matchScore 
            });
        }

        // --- NEW: Sort the list from Highest Match (100%) to Lowest (0%) ---
        matchResults.sort((rowA, rowB) -> Double.compare((Double) rowB[4], (Double) rowA[4]));

        // 5. Push the sorted results into the Dashboard UI Table!
        for (Object[] rowData : matchResults) {
            // We only push the first 4 columns to the UI (Name, Cuisine, Missing, Score)
            // We leave out index 4 (the raw double) because the user doesn't need to see it.
            model.addRow(new Object[]{rowData[0], rowData[1], rowData[2], rowData[3]});
        }
    }//GEN-LAST:event_btnAutoMatchActionPerformed

    private void tblResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultsMouseClicked
       // Only trigger if they DOUBLE CLICK the row
        if (evt.getClickCount() == 2) {
            
            // 1. Find out which row they clicked and get the Recipe Name
            int row = tblResults.getSelectedRow();
            String recipeName = tblResults.getValueAt(row, 0).toString();
            
            // --- NEW: Grab the Score and Missing Items from the Table! ---
            String missingItemsText = tblResults.getValueAt(row, 2).toString();
            String matchScoreText = tblResults.getValueAt(row, 3).toString();
            
            linaer_algo.refinder.model.Recipe recipe = linaer_algo.refinder.database.RecipeDAO.getRecipeByName(recipeName);
            
            if (recipe != null) {
                currentActiveRecipeId = recipe.getId(); 
                
                lblRecipeTitle.setText(recipe.getName());
                lblRecipeCuisine.setText("Cuisine: " + recipe.getCuisine());
                lblRecipeTime.setText("Cook Time: " + recipe.getCookTime() + " mins");
                
                // --- NEW: Set the UI Labels and Conditional Colors ---
                lblMatchScore.setText("Match: " + matchScoreText);
                
                try {
                    // Strip the '%' sign and convert it back to a decimal number
                    double scoreValue = Double.parseDouble(matchScoreText.replace("%", ""));
                    
                    // Apply the Conditional Colors!
                    if (scoreValue >= 50.0) {
                        // Custom darker green for readability
                        lblMatchScore.setForeground(new java.awt.Color(0, 153, 0)); 
                    } else {
                        // Standard red for anything below 50%
                        lblMatchScore.setForeground(java.awt.Color.RED); 
                    }
                } catch (NumberFormatException e) {
                    System.out.println("Could not parse match score for colors.");
                }
                
                lblMissingItems.setText("Missing: " + missingItemsText);
                
                txtRecipeInstructions.setText(recipe.getInstructions());
                
                // 4. Fetch and Format the Ingredients List WITH Quantities and Capitalization
                java.util.List<linaer_algo.refinder.model.Ingredient> fullIngredients = linaer_algo.refinder.database.RecipeDAO.getRecipeIngredients(recipe.getId());
                StringBuilder formattedList = new StringBuilder();
                
                for (linaer_algo.refinder.model.Ingredient ing : fullIngredients) {
                    // Capitalize the first letter of the ingredient name
                    String rawName = ing.getName();
                    String capName = rawName.substring(0, 1).toUpperCase() + rawName.substring(1);
                    
                    // Clean up the decimal (so "1.0" looks like "1", but "1.5" stays "1.5")
                    String qty = String.valueOf(ing.getQuantity());
                    if (qty.endsWith(".0")) {
                        qty = qty.substring(0, qty.length() - 2);
                    }
                    
                    // Build the final string: "- 2 cups Jasmine rice"
                    formattedList.append("- ")
                                 .append(qty).append(" ")
                                 .append(ing.getUnit()).append(" ")
                                 .append(capName).append("\n");
                }
                
                txtRecipeIngredients.setText(formattedList.toString());
                
                // 5. Handle the Recipe Photo
                try {
                    java.net.URL imgURL = getClass().getResource(recipe.getPhotoPath());
                    if(imgURL != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                        java.awt.Image img = icon.getImage().getScaledInstance(lblRecipeImage.getWidth(), lblRecipeImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
                        lblRecipeImage.setIcon(new javax.swing.ImageIcon(img));
                        lblRecipeImage.setText(""); 
                    } else {
                        lblRecipeImage.setIcon(null);
                        lblRecipeImage.setText("No Image Available");
                    }
                } catch (Exception e) {
                    System.out.println("No image loaded.");
                }

                // 6. Flip the CardLayout to show the Recipe Details Screen!
                java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
                layout.show(pnlContent, "pnlRecipeDetails");
            }
        }
    }//GEN-LAST:event_tblResultsMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Flip back to the Dashboard
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
        layout.show(pnlContent, "pnlDashboard"); // Adjust "pnlDashboard" if your card name is different
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookedActionPerformed
       if (currentActiveRecipeId != -1) {
            // 1. Get the exact quantities this recipe needed
            java.util.List<linaer_algo.refinder.model.Ingredient> reqs = linaer_algo.refinder.database.RecipeDAO.getRecipeIngredients(currentActiveRecipeId);
            
            // 2. Loop through and deduct them from the database
            for(linaer_algo.refinder.model.Ingredient req : reqs) {
                linaer_algo.refinder.database.IngredientDAO.deductIngredient(req.getName(), req.getQuantity());
            }
            
            // 3. Add to Cooking Log (Temporary console log until we build the UI)
            System.out.println("LOG: Successfully cooked recipe ID " + currentActiveRecipeId + " at " + java.time.LocalDateTime.now());
            
            // 4. Show a success message to the user
            javax.swing.JOptionPane.showMessageDialog(this, "Ingredients successfully deducted from your inventory! Added to Cooking Log! 🍳");
            
            // 5. Flip back to the dashboard automatically
            java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
            layout.show(pnlContent, "pnlDashboard");
            
            // 6. Optional: Auto-refresh the dashboard table so the inventory updates!
            btnAutoMatch.doClick(); 
        }
    }//GEN-LAST:event_btnCookedActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
        UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (Exception ex) {
        System.err.println("Failed to initialize FlatLaf");
    }

    // Launch the UI
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new MainFrame().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoMatch;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCooked;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnFavorites;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnRecipes;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblInventoryCount;
    private javax.swing.JLabel lblMatchScore;
    private javax.swing.JLabel lblMissingItems;
    private javax.swing.JLabel lblRecipeCuisine;
    private javax.swing.JLabel lblRecipeImage;
    private javax.swing.JLabel lblRecipeTime;
    private javax.swing.JLabel lblRecipeTitle;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlFavorites;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlRecipeDetails;
    private javax.swing.JPanel pnlRecipes;
    private javax.swing.JTable tblResults;
    private javax.swing.JTextArea txtRecipeIngredients;
    private javax.swing.JTextArea txtRecipeInstructions;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void loadButtonIcon(javax.swing.JButton button, String imagePath, int width) {
    try {
        java.net.URL imgURL = getClass().getResource(imagePath);
        if (imgURL != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
            // Scales the icon cleanly
            java.awt.Image scaled = icon.getImage().getScaledInstance(width, -1, java.awt.Image.SCALE_SMOOTH);
            button.setIcon(new javax.swing.ImageIcon(scaled));
        } else {
            System.out.println("Image missing: " + imagePath);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    public void setActiveButton(javax.swing.JButton activeButton) {
        // The default cream color
        java.awt.Color defaultColor = new java.awt.Color(255, 248, 222);
        // A slightly darker tan/cream to show it is selected
        java.awt.Color activeColor = new java.awt.Color(235, 218, 185); 

        // 1. Reset all buttons to default
        btnDashboard.setBackground(defaultColor);
        btnRecipes.setBackground(defaultColor);
        btnInventory.setBackground(defaultColor);
        btnFavorites.setBackground(defaultColor);
        btnLog.setBackground(defaultColor);

        // 2. Highlight the one that was just clicked
        activeButton.setBackground(activeColor);
        
        
    }
}
