/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package linaer_algo.refinder.ui;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import linaer_algo.refinder.database.IngredientDAO;
import linaer_algo.refinder.database.RecipeDAO;
import linaer_algo.refinder.model.Recipe;
import linaer_algo.refinder.model.Ingredient;
import linaer_algo.refinder.algorithm.RabinKarp;
/**
 *
 * @author Joko1
 */
public class MainFrame extends javax.swing.JFrame {
    
    private int currentActiveRecipeId = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        loadInventoryTable();
        loadRecipeCards("");
        
        loadButtonIcon(btnDashboard, "/home.png", 25);
        loadButtonIcon(btnRecipes, "/cookbook.png", 25);
        loadButtonIcon(btnInventory, "/fridge.png", 25);
        loadButtonIcon(btnFavorites, "/star.png", 25);
        loadButtonIcon(btnLog, "/history.png", 25);
        
        setActiveButton(btnDashboard);
        
        
        if (!linaer_algo.refinder.database.IngredientDAO.ingredientExists("chicken")) {
            linaer_algo.refinder.database.IngredientDAO.addIngredient(new linaer_algo.refinder.model.Ingredient(0, "chicken", 1.0, "kg"));
            linaer_algo.refinder.database.IngredientDAO.addIngredient(new linaer_algo.refinder.model.Ingredient(0, "garlic", 3.0, "cloves"));
            linaer_algo.refinder.database.IngredientDAO.addIngredient(new linaer_algo.refinder.model.Ingredient(0, "soy sauce", 1.0, "bottle"));
            System.out.println("Test ingredients added successfully!");
        }
        
        // --- NEW: Style the Table Headers! ---
        javax.swing.table.JTableHeader header = tblInventory.getTableHeader();
        // Set to your rust/brown theme color (Adjust these RGB numbers if needed!)
        header.setBackground(new java.awt.Color(164, 61, 23)); 
        header.setForeground(java.awt.Color.WHITE); // White text so it pops
        header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12)); // Make it bold
        header.setOpaque(false); // Forces Java to apply the background color
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnFavorites = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnRecipes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnlContent = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        lblGreeting = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        btnAutoMatch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblInventoryCount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        pnlDashboardCards = new javax.swing.JPanel();
        pnlRecipes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlRecipeCards = new javax.swing.JPanel();
        pnlInventory = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtIngName = new javax.swing.JTextField();
        txtIngQty = new javax.swing.JTextField();
        cmbIngUnit = new javax.swing.JComboBox<>();
        btnAdding = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblTotalItems = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        lblRecentAdd = new javax.swing.JLabel();
        pnlFavorites = new javax.swing.JPanel();
        pnlLog = new javax.swing.JPanel();
        pnlRecipeDetails = new javax.swing.JPanel();
        lblRecipeImage = new javax.swing.JLabel();
        lblRecipeTitle = new javax.swing.JLabel();
        lblRecipeCuisine = new javax.swing.JLabel();
        lblRecipeTime = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRecipeIngredients = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtRecipeInstructions = new javax.swing.JTextArea();
        btnCooked = new javax.swing.JButton();
        lblMatchScore = new javax.swing.JLabel();
        lblMissingItems = new javax.swing.JLabel();
        btnFavorite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 248, 222));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(255, 248, 222));

        jPanel1.setBackground(new java.awt.Color(160, 58, 19));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 4, new java.awt.Color(93, 52, 21)));
        jPanel1.setPreferredSize(new java.awt.Dimension(220, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 248, 222));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copy.png"))); // NOI18N
        jLabel1.setText("ReFinder");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(-30);

        btnDashboard.setBackground(new java.awt.Color(255, 248, 222));
        btnDashboard.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(93, 39, 14));
        btnDashboard.setText("   Dashboard");
        btnDashboard.setFocusPainted(false);
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setIconTextGap(15);
        btnDashboard.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnInventory.setBackground(new java.awt.Color(255, 248, 222));
        btnInventory.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnInventory.setForeground(new java.awt.Color(93, 39, 14));
        btnInventory.setText(" Inventory");
        btnInventory.setFocusPainted(false);
        btnInventory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInventory.setIconTextGap(15);
        btnInventory.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnInventory.addActionListener(this::btnInventoryActionPerformed);

        btnFavorites.setBackground(new java.awt.Color(255, 248, 222));
        btnFavorites.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnFavorites.setForeground(new java.awt.Color(93, 39, 14));
        btnFavorites.setText(" Favorites");
        btnFavorites.setFocusPainted(false);
        btnFavorites.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFavorites.setIconTextGap(15);
        btnFavorites.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnFavorites.addActionListener(this::btnFavoritesActionPerformed);

        btnLog.setBackground(new java.awt.Color(255, 248, 222));
        btnLog.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnLog.setForeground(new java.awt.Color(93, 39, 14));
        btnLog.setText(" Cooking Log");
        btnLog.setFocusPainted(false);
        btnLog.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLog.setIconTextGap(15);
        btnLog.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnLog.addActionListener(this::btnLogActionPerformed);

        btnRecipes.setBackground(new java.awt.Color(255, 248, 222));
        btnRecipes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRecipes.setForeground(new java.awt.Color(93, 39, 14));
        btnRecipes.setText("  Recipes");
        btnRecipes.setFocusPainted(false);
        btnRecipes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRecipes.setIconTextGap(15);
        btnRecipes.setMargin(new java.awt.Insets(2, 20, 3, 14));
        btnRecipes.addActionListener(this::btnRecipesActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFavorites, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInventory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecipes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFavorites, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlContent.setLayout(new java.awt.CardLayout());

        pnlDashboard.setBackground(new java.awt.Color(255, 248, 222));
        pnlDashboard.setPreferredSize(new java.awt.Dimension(3000, 760));

        lblGreeting.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        lblGreeting.setForeground(new java.awt.Color(160, 58, 19));
        lblGreeting.setText("Good Morning!");

        lblSubtitle.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(93, 39, 14));
        lblSubtitle.setText("What do you wanna cook today?");

        btnAutoMatch.setBackground(new java.awt.Color(160, 58, 19));
        btnAutoMatch.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnAutoMatch.setForeground(new java.awt.Color(255, 248, 222));
        btnAutoMatch.setText("What can I cook?");
        btnAutoMatch.addActionListener(this::btnAutoMatchActionPerformed);

        txtSearch.setBackground(new java.awt.Color(160, 58, 19));
        txtSearch.setForeground(new java.awt.Color(255, 248, 222));

        btnSearch.setBackground(new java.awt.Color(160, 58, 19));
        btnSearch.setForeground(new java.awt.Color(255, 248, 222));
        btnSearch.setText("Search");

        lblInventoryCount.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblInventoryCount.setForeground(new java.awt.Color(160, 58, 19));
        lblInventoryCount.setText("Items in Inventory: ");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(160, 58, 19));
        jLabel3.setText("Total  Recipes: 60");
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jSeparator2.setBackground(new java.awt.Color(160, 58, 19));

        jLabel2.setBackground(new java.awt.Color(160, 58, 19));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(160, 58, 19));
        jLabel2.setText("Manual Search:");

        pnlDashboardCards.setBackground(new java.awt.Color(255, 248, 222));
        jScrollPane5.setViewportView(pnlDashboardCards);

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAutoMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1867, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDashboardLayout.createSequentialGroup()
                                    .addComponent(lblInventoryCount)
                                    .addGap(1423, 1423, 1423)
                                    .addComponent(jLabel3)))
                            .addComponent(lblSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGreeting)
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1133, Short.MAX_VALUE))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblGreeting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubtitle)
                .addGap(41, 41, 41)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAutoMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblInventoryCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pnlContent.add(pnlDashboard, "pnlDashboard");

        pnlRecipes.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout pnlRecipeCardsLayout = new javax.swing.GroupLayout(pnlRecipeCards);
        pnlRecipeCards.setLayout(pnlRecipeCardsLayout);
        pnlRecipeCardsLayout.setHorizontalGroup(
            pnlRecipeCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1553, Short.MAX_VALUE)
        );
        pnlRecipeCardsLayout.setVerticalGroup(
            pnlRecipeCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlRecipeCards);

        javax.swing.GroupLayout pnlRecipesLayout = new javax.swing.GroupLayout(pnlRecipes);
        pnlRecipes.setLayout(pnlRecipesLayout);
        pnlRecipesLayout.setHorizontalGroup(
            pnlRecipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        pnlRecipesLayout.setVerticalGroup(
            pnlRecipesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pnlContent.add(pnlRecipes, "pnlRecipes");

        pnlInventory.setBackground(new java.awt.Color(255, 255, 204));

        jPanel3.setBackground(new java.awt.Color(160, 58, 19));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 58, 19), 3, true));

        txtIngName.setBackground(new java.awt.Color(255, 248, 222));
        txtIngName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtIngName.setForeground(new java.awt.Color(160, 58, 19));

        txtIngQty.setBackground(new java.awt.Color(255, 248, 222));
        txtIngQty.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtIngQty.setForeground(new java.awt.Color(160, 58, 19));

        cmbIngUnit.setBackground(new java.awt.Color(255, 248, 222));
        cmbIngUnit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cmbIngUnit.setForeground(new java.awt.Color(160, 58, 19));
        cmbIngUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cloves", "g", "kg", "piece" }));

        btnAdding.setBackground(new java.awt.Color(255, 248, 222));
        btnAdding.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        btnAdding.setForeground(new java.awt.Color(160, 58, 19));
        btnAdding.setText("Add");
        btnAdding.addActionListener(this::btnAddingActionPerformed);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 248, 222));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/copy.png"))); // NOI18N
        jLabel5.setText("ReFinder");
        jLabel5.setIconTextGap(-30);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIngQty, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbIngUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtIngName, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(312, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIngName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIngQty, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbIngUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdding, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jScrollPane4.setBackground(new java.awt.Color(242, 230, 185));

        tblInventory.setBackground(new java.awt.Color(242, 230, 185));
        tblInventory.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ingredients Name", "Quantity", "Unit"
            }
        ));
        jScrollPane4.setViewportView(tblInventory);
        if (tblInventory.getColumnModel().getColumnCount() > 0) {
            tblInventory.getColumnModel().getColumn(1).setResizable(false);
            tblInventory.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 4, true));

        lblTotalItems.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblTotalItems.setForeground(new java.awt.Color(160, 58, 19));
        lblTotalItems.setText("Total Unique Ingredients: 0");

        lblLowStock.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblLowStock.setForeground(new java.awt.Color(160, 58, 19));
        lblLowStock.setText("Low Stock Items : 0");

        lblRecentAdd.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        lblRecentAdd.setForeground(new java.awt.Color(160, 58, 19));
        lblRecentAdd.setText("Last Added: None");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLowStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotalItems, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addComponent(lblRecentAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTotalItems, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLowStock, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRecentAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlInventoryLayout = new javax.swing.GroupLayout(pnlInventory);
        pnlInventory.setLayout(pnlInventoryLayout);
        pnlInventoryLayout.setHorizontalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        pnlInventoryLayout.setVerticalGroup(
            pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventoryLayout.createSequentialGroup()
                .addGroup(pnlInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInventoryLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pnlContent.add(pnlInventory, "pnlInventory");

        pnlFavorites.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout pnlFavoritesLayout = new javax.swing.GroupLayout(pnlFavorites);
        pnlFavorites.setLayout(pnlFavoritesLayout);
        pnlFavoritesLayout.setHorizontalGroup(
            pnlFavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1782, Short.MAX_VALUE)
        );
        pnlFavoritesLayout.setVerticalGroup(
            pnlFavoritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );

        pnlContent.add(pnlFavorites, "pnlFavorites");

        pnlLog.setBackground(new java.awt.Color(255, 102, 255));

        javax.swing.GroupLayout pnlLogLayout = new javax.swing.GroupLayout(pnlLog);
        pnlLog.setLayout(pnlLogLayout);
        pnlLogLayout.setHorizontalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1782, Short.MAX_VALUE)
        );
        pnlLogLayout.setVerticalGroup(
            pnlLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1025, Short.MAX_VALUE)
        );

        pnlContent.add(pnlLog, "pnlLog");

        pnlRecipeDetails.setBackground(new java.awt.Color(255, 248, 222));

        lblRecipeImage.setText("jLabel4");
        lblRecipeImage.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(160, 58, 19)));

        lblRecipeTitle.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblRecipeTitle.setForeground(new java.awt.Color(160, 58, 19));
        lblRecipeTitle.setText("jLabel4");

        lblRecipeCuisine.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblRecipeCuisine.setForeground(new java.awt.Color(160, 58, 19));
        lblRecipeCuisine.setText("jLabel4");

        lblRecipeTime.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblRecipeTime.setForeground(new java.awt.Color(160, 58, 19));
        lblRecipeTime.setText("jLabel5");

        btnBack.setBackground(new java.awt.Color(160, 58, 19));
        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        txtRecipeIngredients.setBackground(new java.awt.Color(255, 248, 222));
        txtRecipeIngredients.setColumns(20);
        txtRecipeIngredients.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtRecipeIngredients.setForeground(new java.awt.Color(160, 58, 19));
        txtRecipeIngredients.setLineWrap(true);
        txtRecipeIngredients.setRows(5);
        txtRecipeIngredients.setWrapStyleWord(true);
        txtRecipeIngredients.setBorder(null);
        jScrollPane2.setViewportView(txtRecipeIngredients);

        txtRecipeInstructions.setBackground(new java.awt.Color(255, 248, 222));
        txtRecipeInstructions.setColumns(20);
        txtRecipeInstructions.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        txtRecipeInstructions.setForeground(new java.awt.Color(160, 58, 19));
        txtRecipeInstructions.setLineWrap(true);
        txtRecipeInstructions.setRows(5);
        txtRecipeInstructions.setWrapStyleWord(true);
        txtRecipeInstructions.setBorder(null);
        jScrollPane3.setViewportView(txtRecipeInstructions);

        btnCooked.setBackground(new java.awt.Color(160, 58, 19));
        btnCooked.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCooked.setText("I COOKED THIS");
        btnCooked.addActionListener(this::btnCookedActionPerformed);

        lblMatchScore.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMatchScore.setText("jLabel4");

        lblMissingItems.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        lblMissingItems.setText("jLabel5");

        btnFavorite.setBackground(new java.awt.Color(160, 58, 19));
        btnFavorite.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnFavorite.setText("Bookmark");
        btnFavorite.addActionListener(this::btnFavoriteActionPerformed);

        javax.swing.GroupLayout pnlRecipeDetailsLayout = new javax.swing.GroupLayout(pnlRecipeDetails);
        pnlRecipeDetails.setLayout(pnlRecipeDetailsLayout);
        pnlRecipeDetailsLayout.setHorizontalGroup(
            pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecipeCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecipeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMatchScore, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMissingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE))
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3)
                        .addGap(15, 15, 15)))
                .addGap(32, 32, 32)
                .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCooked, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addComponent(btnFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnlRecipeDetailsLayout.setVerticalGroup(
            pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRecipeCuisine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRecipeTime, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMatchScore, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMissingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRecipeDetailsLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblRecipeImage, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlRecipeDetailsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlRecipeDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnFavorite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCooked, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pnlContent.add(pnlRecipeDetails, "pnlRecipeDetails");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFavoritesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoritesActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnFavorites);
        
        pnlContent.removeAll();
        pnlContent.add(pnlFavorites);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnFavoritesActionPerformed

    private void btnRecipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecipesActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnRecipes);
        
        pnlContent.removeAll();
        pnlContent.add(pnlRecipes);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnRecipesActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnDashboard); // Highlight the button
        
        // Tell the CardLayout to show the Dashboard panel
        pnlContent.removeAll();
        pnlContent.add(pnlDashboard);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnInventory);
        
        pnlContent.removeAll();
        pnlContent.add(pnlInventory);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        setActiveButton(btnLog);
        
        pnlContent.removeAll();
        pnlContent.add(pnlLog);
        pnlContent.repaint();
        pnlContent.revalidate();
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnAutoMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoMatchActionPerformed
      // 1. Clear the card container from any previous searches
        pnlDashboardCards.removeAll();

        // 2. Fetch User Inventory
        java.util.List<linaer_algo.refinder.model.Ingredient> myInventory = linaer_algo.refinder.database.IngredientDAO.getAllIngredients();

        // 3. Fetch All Recipes
        java.util.List<linaer_algo.refinder.model.Recipe> allRecipes = linaer_algo.refinder.database.RecipeDAO.getAllRecipes();
        java.util.List<Object[]> matchResults = new java.util.ArrayList<>();

        // 4. Run the True Rolling Hash + Quantity Check
        for (linaer_algo.refinder.model.Recipe recipe : allRecipes) {
            java.util.List<linaer_algo.refinder.model.Ingredient> requiredIngredients = linaer_algo.refinder.database.RecipeDAO.getRecipeIngredients(recipe.getId());
            
            double matchScore = linaer_algo.refinder.algorithm.RabinKarp.calculateQuantityMatch(requiredIngredients, myInventory);
            java.util.List<String> missing = linaer_algo.refinder.algorithm.RabinKarp.getMissingQuantityIngredients(requiredIngredients, myInventory);
            
            String missingItems = String.join(", ", missing);
            if (missingItems.isEmpty()) {
                missingItems = "Ready to cook! 🍳";
            }
            
            matchResults.add(new Object[]{recipe, matchScore, missingItems});
        }

        // 5. Sort from Highest Match (100%) to Lowest (0%)
        matchResults.sort((rowA, rowB) -> Double.compare((Double) rowB[1], (Double) rowA[1]));

        // --- 6. BUILD THE CARDS DYNAMICALLY ---
        for (Object[] rowData : matchResults) {
            linaer_algo.refinder.model.Recipe recipe = (linaer_algo.refinder.model.Recipe) rowData[0];
            double score = (Double) rowData[1];
            String missingItems = (String) rowData[2];

            // Create the main Card Panel
            javax.swing.JPanel card = new javax.swing.JPanel();
            card.setPreferredSize(new java.awt.Dimension(220, 280)); 
            card.setBackground(new java.awt.Color(255, 240, 230));
            card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 248, 222), 2, true)); // Cream Border
            card.setLayout(new java.awt.BorderLayout());

            // Image Section
            javax.swing.JLabel lblImg = new javax.swing.JLabel();
            lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            try {
                java.net.URL imgURL = getClass().getResource(recipe.getPhotoPath());
                if (imgURL != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                    java.awt.Image img = icon.getImage().getScaledInstance(200, 150, java.awt.Image.SCALE_SMOOTH);
                    lblImg.setIcon(new javax.swing.ImageIcon(img));
                } else {
                    lblImg.setText("No Image");
                }
            } catch (Exception e) {}

            // Text Section (Title, Score, Missing Items)
            javax.swing.JPanel pnlText = new javax.swing.JPanel(new java.awt.GridLayout(3, 1));
            pnlText.setBackground(new java.awt.Color(255, 240, 230)); // Dark Orange!
            pnlText.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)); 
            
            // Recipe Name
            javax.swing.JLabel lblTitle = new javax.swing.JLabel(recipe.getName(), javax.swing.SwingConstants.CENTER);
            lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
            lblTitle.setForeground(new java.awt.Color(160, 58, 19)); 
            
            // Match Percentage (Color coded!)
            String formattedScore = String.format("%.1f%% Match", score);
            javax.swing.JLabel lblScore = new javax.swing.JLabel(formattedScore, javax.swing.SwingConstants.CENTER);
            lblScore.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
            
            if (score >= 50.0) {
                lblScore.setForeground(new java.awt.Color(0, 153, 0)); // Green if 50% or higher
            } else {
                lblScore.setForeground(java.awt.Color.RED); // Pure Red if below 50%
            }
            
            // Missing Items
            javax.swing.JLabel lblMiss = new javax.swing.JLabel(missingItems, javax.swing.SwingConstants.CENTER);
            lblMiss.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));
            lblMiss.setForeground(new java.awt.Color(220, 220, 220));

            pnlText.add(lblTitle);
            pnlText.add(lblScore);
            pnlText.add(lblMiss);

            card.add(lblImg, java.awt.BorderLayout.CENTER);
            card.add(pnlText, java.awt.BorderLayout.SOUTH);

            // Add Click Event to open the Recipe Details
            final int finalId = recipe.getId();
            final double finalScore = score;
            final String finalMissing = missingItems;
            
            card.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    openRecipeDetailsFromDashboard(finalId, finalScore, finalMissing);
                }
                public void mouseEntered(java.awt.event.MouseEvent evt) {
                    card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(160, 58, 19), 2, true)); // Hover effect
                }
                public void mouseExited(java.awt.event.MouseEvent evt) {
                    card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));
                }
            });

            // Drop it into the UI
            pnlDashboardCards.add(card);
        }

        // --- NEW FIX: Force Vertical Scrolling (OUTSIDE the loop!) ---
        pnlDashboardCards.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 8, 8));
        int totalCards = matchResults.size();
        int estimatedRows = (int) Math.ceil(totalCards / 6.0); 
        pnlDashboardCards.setPreferredSize(new java.awt.Dimension(1400, (estimatedRows * 310) + 100));

        pnlDashboardCards.revalidate();
        pnlDashboardCards.repaint();
    }//GEN-LAST:event_btnAutoMatchActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        // Flip back to the Dashboard
        java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
        layout.show(pnlContent, "pnlDashboard"); // Adjust "pnlDashboard" if your card name is different
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCookedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCookedActionPerformed
       if (currentActiveRecipeId != -1) {
            // 1. Get the exact quantities this recipe needed
            java.util.List<linaer_algo.refinder.model.Ingredient> reqs = linaer_algo.refinder.database.RecipeDAO.getRecipeIngredients(currentActiveRecipeId);
            
            // 2. Loop through and deduct them from the database
            for(linaer_algo.refinder.model.Ingredient req : reqs) {
                linaer_algo.refinder.database.IngredientDAO.deductIngredient(req.getName(), req.getQuantity());
            }
            
            // 3. Add to Cooking Log (Temporary console log until we build the UI)
            System.out.println("LOG: Successfully cooked recipe ID " + currentActiveRecipeId + " at " + java.time.LocalDateTime.now());
            
            // 4. Show a success message to the user
            javax.swing.JOptionPane.showMessageDialog(this, "Ingredients successfully deducted from your inventory! Added to Cooking Log! 🍳");
            
            // 5. Flip back to the dashboard automatically
            java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
            layout.show(pnlContent, "pnlDashboard");
            
            // 6. Optional: Auto-refresh the dashboard table so the inventory updates!
            btnAutoMatch.doClick(); 
        }
    }//GEN-LAST:event_btnCookedActionPerformed

    private void btnAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddingActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Grab the data from the UI
            String name = txtIngName.getText().trim();
            String qtyText = txtIngQty.getText().trim();
            String unit = cmbIngUnit.getSelectedItem().toString();

            // Safety check so they don't add blank stuff
            if (name.isEmpty() || qtyText.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter both a name and a quantity!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Convert text to a number (this is where we check if they typed letters by accident)
            double qty = Double.parseDouble(qtyText);

            // 3. Send it to the database! 
            linaer_algo.refinder.database.IngredientDAO.addOrUpdateIngredient(name, qty, unit);

            // 4. Clear the text boxes so they can add the next thing easily
            txtIngName.setText("");
            txtIngQty.setText("");
            txtIngName.requestFocus(); // Puts the typing cursor back in the name box!

            // 5. Update the "Last Added" stat on your floating card
            lblRecentAdd.setText("Last Added: " + name.substring(0, 1).toUpperCase() + name.substring(1));

            // 6. Refresh the table and the rest of the stats instantly!
            loadInventoryTable(); 
            
            // Optional: Little success pop-up
            javax.swing.JOptionPane.showMessageDialog(this, "Added to Inventory! 🥦");

        } catch (NumberFormatException e) {
            // Catches them if they type "five" instead of "5"
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be a number!", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddingActionPerformed

    private void btnFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFavoriteActionPerformed
        // TODO add your handling code here:
        if (currentActiveRecipeId != -1) {
            
            // 1. Check if it is already favorited using YOUR custom method!
            boolean alreadySaved = linaer_algo.refinder.database.RecipeDAO.isFavorite(currentActiveRecipeId);
            
            if (alreadySaved) {
                // Let them know they already saved it
                javax.swing.JOptionPane.showMessageDialog(this, "This recipe is already in your Favorites! ❤️", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                // 2. Not saved yet? Add it using YOUR custom method!
                linaer_algo.refinder.database.RecipeDAO.addToFavorites(currentActiveRecipeId);
                javax.swing.JOptionPane.showMessageDialog(this, "Recipe successfully saved to your Favorites! ❤️");
            }
        }
    }//GEN-LAST:event_btnFavoriteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
        UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (Exception ex) {
        System.err.println("Failed to initialize FlatLaf");
    }

    // Launch the UI
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new MainFrame().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdding;
    private javax.swing.JButton btnAutoMatch;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCooked;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnFavorite;
    private javax.swing.JButton btnFavorites;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnRecipes;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbIngUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblGreeting;
    private javax.swing.JLabel lblInventoryCount;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblMatchScore;
    private javax.swing.JLabel lblMissingItems;
    private javax.swing.JLabel lblRecentAdd;
    private javax.swing.JLabel lblRecipeCuisine;
    private javax.swing.JLabel lblRecipeImage;
    private javax.swing.JLabel lblRecipeTime;
    private javax.swing.JLabel lblRecipeTitle;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTotalItems;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDashboardCards;
    private javax.swing.JPanel pnlFavorites;
    private javax.swing.JPanel pnlInventory;
    private javax.swing.JPanel pnlLog;
    private javax.swing.JPanel pnlRecipeCards;
    private javax.swing.JPanel pnlRecipeDetails;
    private javax.swing.JPanel pnlRecipes;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTextField txtIngName;
    private javax.swing.JTextField txtIngQty;
    private javax.swing.JTextArea txtRecipeIngredients;
    private javax.swing.JTextArea txtRecipeInstructions;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public void loadButtonIcon(javax.swing.JButton button, String imagePath, int width) {
    try {
        java.net.URL imgURL = getClass().getResource(imagePath);
        if (imgURL != null) {
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
            // Scales the icon cleanly
            java.awt.Image scaled = icon.getImage().getScaledInstance(width, -1, java.awt.Image.SCALE_SMOOTH);
            button.setIcon(new javax.swing.ImageIcon(scaled));
        } else {
            System.out.println("Image missing: " + imagePath);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    public void setActiveButton(javax.swing.JButton activeButton) {
        // The default cream color
        java.awt.Color defaultColor = new java.awt.Color(255, 248, 222);
        // A slightly darker tan/cream to show it is selected
        java.awt.Color activeColor = new java.awt.Color(235, 218, 185); 

        // 1. Reset all buttons to default
        btnDashboard.setBackground(defaultColor);
        btnRecipes.setBackground(defaultColor);
        btnInventory.setBackground(defaultColor);
        btnFavorites.setBackground(defaultColor);
        btnLog.setBackground(defaultColor);

        // 2. Highlight the one that was just clicked
        activeButton.setBackground(activeColor);
        
        
    }
    
    public void loadInventoryTable() {
        // 1. Get the table model and wipe it clean before loading fresh data
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblInventory.getModel();
        model.setRowCount(0); 

        int totalItems = 0;
        int lowStockCount = 0;

        // 2. Fetch data from SQLite, sorted alphabetically!
        String sql = "SELECT name, quantity, unit FROM ingredients ORDER BY name ASC";
        
        try (java.sql.Connection conn = linaer_algo.refinder.database.DatabaseConnection.getConnection();
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                String rawName = rs.getString("name");
                double qty = rs.getDouble("quantity");
                String unit = rs.getString("unit");

                // Capitalize the first letter so it looks professional in the table
                String capName = rawName.substring(0, 1).toUpperCase() + rawName.substring(1);

                // Add the row to the table!
                model.addRow(new Object[]{capName, qty, unit});

                // 3. Do the Math for our Stats Board!
                totalItems++;
                if (qty < 2.0) {
                    lowStockCount++;
                }
            }

            // 4. Update the UI Labels
            lblTotalItems.setText("Total Unique Ingredients: " + totalItems);
            lblLowStock.setText("Low Stock Items (< 2 units): " + lowStockCount);

            // 5. Apply the Dynamic Red Warning Text!
            if (lowStockCount > 0) {
                lblLowStock.setForeground(java.awt.Color.RED);
            } else {
                lblLowStock.setForeground(new java.awt.Color(50, 50, 50)); // Dark gray
            }

        } catch (Exception e) {
            System.out.println("Error loading inventory: " + e.getMessage());
        }
    }
    
   public void loadRecipeCards(String searchQuery) {
        // 1. Clear the container so we don't stack duplicates
        pnlRecipeCards.removeAll(); 
        
        String sql = "SELECT id, name, cook_time, photo_path FROM recipes";
        if (searchQuery != null && !searchQuery.trim().isEmpty()) {
            sql += " WHERE LOWER(name) LIKE '%" + searchQuery.toLowerCase() + "%'";
        }
        sql += " ORDER BY name ASC";

        try (java.sql.Connection conn = linaer_algo.refinder.database.DatabaseConnection.getConnection();
             java.sql.Statement stmt = conn.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(sql)) {

            while (rs.next()) {
                final int recipeId = rs.getInt("id"); 
                String name = rs.getString("name");
                int time = rs.getInt("cook_time");
                String photoPath = rs.getString("photo_path");

                // --- 2. BUILD THE CARD ---
                javax.swing.JPanel card = new javax.swing.JPanel();
                card.setPreferredSize(new java.awt.Dimension(200, 240)); 
                card.setBackground(new java.awt.Color(255, 240, 230));
                card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 248, 222), 2, true)); // Cream Border
                card.setLayout(new java.awt.BorderLayout());

                // --- 3. ADD THE IMAGE ---
                javax.swing.JLabel lblImg = new javax.swing.JLabel();
                lblImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                try {
                    java.net.URL imgURL = getClass().getResource(photoPath);
                    if (imgURL != null) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                        java.awt.Image img = icon.getImage().getScaledInstance(180, 160, java.awt.Image.SCALE_SMOOTH);
                        lblImg.setIcon(new javax.swing.ImageIcon(img));
                    } else {
                        lblImg.setText("No Image");
                    }
                } catch (Exception e) {}

                // --- 4. ADD THE TEXT ---
                javax.swing.JPanel pnlText = new javax.swing.JPanel(new java.awt.GridLayout(2, 1));
                pnlText.setBackground(new java.awt.Color(255, 248, 222)); // Changed to Cream!
                pnlText.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)); 
                
                javax.swing.JLabel lblTitle = new javax.swing.JLabel(name, javax.swing.SwingConstants.CENTER);
                lblTitle.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
                
                javax.swing.JLabel lblTime = new javax.swing.JLabel("🕒 " + time + " mins", javax.swing.SwingConstants.CENTER);
                lblTime.setForeground(new java.awt.Color(100, 100, 100)); 

                pnlText.add(lblTitle);
                pnlText.add(lblTime);

                // --- 5. ASSEMBLE THE CARD ---
                card.add(lblImg, java.awt.BorderLayout.CENTER);
                card.add(pnlText, java.awt.BorderLayout.SOUTH);

                // --- 6. ADD CLICK EVENT ---
                card.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        openRecipeDetailsFromCard(recipeId); 
                    }
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(164, 61, 23), 2, true));
                    }
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true)); 
                    }
                });

                // --- 7. DROP CARD INTO THE RECIPES GRID ---
                pnlRecipeCards.add(card);
            }

            // --- NEW FIX: Force Vertical Scrolling (OUTSIDE the while loop!) ---
            pnlRecipeCards.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 20, 20));
            int totalCards = pnlRecipeCards.getComponentCount();
            int estimatedRows = (int) Math.ceil(totalCards / 6.0); 
            pnlRecipeCards.setPreferredSize(new java.awt.Dimension(1400, (estimatedRows * 310) + 100));

            pnlRecipeCards.revalidate();
            pnlRecipeCards.repaint();

        } catch (Exception e) {
            System.out.println("Error loading recipe cards: " + e.getMessage());
        }
    }
    
    public void openRecipeDetailsFromCard(int id) {
        // Fetch it from the database using the ID!
        linaer_algo.refinder.model.Recipe recipe = null;
        for(linaer_algo.refinder.model.Recipe r : linaer_algo.refinder.database.RecipeDAO.getAllRecipes()) {
             if(r.getId() == id) { recipe = r; break; }
        }
        
        if (recipe != null) {
            currentActiveRecipeId = recipe.getId(); 
            
            lblRecipeTitle.setText(recipe.getName());
            lblRecipeCuisine.setText("Cuisine: " + recipe.getCuisine());
            lblRecipeTime.setText("Cook Time: " + recipe.getCookTime() + " mins");
            txtRecipeInstructions.setText(recipe.getInstructions());
            lblMatchScore.setText(""); 
            lblMissingItems.setText("Viewing from Recipe Directory"); 
            
            // Load Ingredients
            java.util.List<linaer_algo.refinder.model.Ingredient> fullIngredients = linaer_algo.refinder.database.RecipeDAO.getRecipeIngredients(recipe.getId());
            StringBuilder formattedList = new StringBuilder();
            for (linaer_algo.refinder.model.Ingredient ing : fullIngredients) {
                String capName = ing.getName().substring(0, 1).toUpperCase() + ing.getName().substring(1);
                String qty = String.valueOf(ing.getQuantity());
                if (qty.endsWith(".0")) qty = qty.substring(0, qty.length() - 2);
                formattedList.append("- ").append(qty).append(" ").append(ing.getUnit()).append(" ").append(capName).append("\n");
            }
            txtRecipeIngredients.setText(formattedList.toString());
            
            // Load Photo
            try {
                java.net.URL imgURL = getClass().getResource(recipe.getPhotoPath());
                if(imgURL != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                    java.awt.Image img = icon.getImage().getScaledInstance(lblRecipeImage.getWidth(), lblRecipeImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    lblRecipeImage.setIcon(new javax.swing.ImageIcon(img));
                }
            } catch (Exception e) {}

            // Flip screen
            java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
            layout.show(pnlContent, "pnlRecipeDetails");
        }
    }
    
    public void openRecipeDetailsFromDashboard(int id, double matchScore, String missingItems) {
        linaer_algo.refinder.model.Recipe recipe = linaer_algo.refinder.database.RecipeDAO.getRecipeByName(
            linaer_algo.refinder.database.RecipeDAO.getAllRecipes().stream().filter(r -> r.getId() == id).findFirst().get().getName()
        );
        
        if (recipe != null) {
            currentActiveRecipeId = recipe.getId(); 
            
            // Load text
            lblRecipeTitle.setText(recipe.getName());
            lblRecipeCuisine.setText("Cuisine: " + recipe.getCuisine());
            lblRecipeTime.setText("Cook Time: " + recipe.getCookTime() + " mins");
            txtRecipeInstructions.setText(recipe.getInstructions());
            
            // Load Algorithm Stats!
            lblMatchScore.setText(String.format("Match Score: %.1f%%", matchScore));
            if (matchScore >= 80.0) {
                lblMatchScore.setForeground(new java.awt.Color(0, 153, 0));
            } else {
                lblMatchScore.setForeground(java.awt.Color.RED);
            }
            lblMissingItems.setText("Missing: " + missingItems); 
            
            // Load Ingredients List
            java.util.List<linaer_algo.refinder.model.Ingredient> fullIngredients = linaer_algo.refinder.database.RecipeDAO.getRecipeIngredients(recipe.getId());
            StringBuilder formattedList = new StringBuilder();
            for (linaer_algo.refinder.model.Ingredient ing : fullIngredients) {
                String capName = ing.getName().substring(0, 1).toUpperCase() + ing.getName().substring(1);
                String qty = String.valueOf(ing.getQuantity());
                if (qty.endsWith(".0")) qty = qty.substring(0, qty.length() - 2);
                formattedList.append("- ").append(qty).append(" ").append(ing.getUnit()).append(" ").append(capName).append("\n");
            }
            txtRecipeIngredients.setText(formattedList.toString());
            
            // Load Photo
            try {
                java.net.URL imgURL = getClass().getResource(recipe.getPhotoPath());
                if(imgURL != null) {
                    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(imgURL);
                    java.awt.Image img = icon.getImage().getScaledInstance(lblRecipeImage.getWidth(), lblRecipeImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    lblRecipeImage.setIcon(new javax.swing.ImageIcon(img));
                }
            } catch (Exception e) {}

            // Flip screen
            java.awt.CardLayout layout = (java.awt.CardLayout) pnlContent.getLayout();
            layout.show(pnlContent, "pnlRecipeDetails");
        }
    }
}
